### ISSUE TITLE
Plaintext version of the blog list

### ISSUE THREAD

**Issue by lodenrogue** [outcoldman/hackernews-personal-blogs#10]
Is there any way you can provide and maintain a plaintext version of the blog list so I can use it in my own program to explore these blogs?

I'm not really interested in exploring them in an RSS reader.

Maybe something like csv
```
name,url
jgrahamc,https://blog.jgc.org/
...
```

**Comment by outcoldman** [comment]
You can use something like [xq](https://github.com/jeffbr13/xq) to convert OLMP to csv.

**Comment by lodenrogue** [comment]
Thanks!
