### ISSUE TITLE
HN Post is Closed to Comments

### ISSUE THREAD

**Issue by acnolan** [outcoldman/hackernews-personal-blogs#11]
The [Hacker News post](https://news.ycombinator.com/item?id=36575081)  to submit blogs is now more than 2 weeks old. This means it is closed to new comments.

Is there another way that people can submit their blogs to the list?

**Comment by outcoldman** [comment]
Hello, I would say maybe create a new opml file, name it `listx.opml`, and manually add a blog to it

```
<?xml version="1.0" encoding="UTF-8"?>
<opml version="2.0">
<head>
<title>Hacker News Personal Blogs</title>
</head>
<body>
<outline title="HN Personal Blogs (After submission)" text="HN Personal Blogs (After submission)">
    <outline type="rss" title="user1" text="user1" xmlUrl="https://user1.com/feed.xml" htmlUrl="https:/user1.com/feed.xml"/>
</outline>
</body>
</opml>
```

**Comment by acnolan** [comment]
Sounds good, created a PR for that: https://github.com/outcoldman/hackernews-personal-blogs/pull/12

**Comment by outcoldman** [comment]
Done!
