### ISSUE TITLE
Some addresses needs sanitization

### ISSUE THREAD

**Issue by jared52005** [outcoldman/hackernews-personal-blogs#9]
Some addresses are not reachable via RSS reader because they contain invalid characters:
* double `//`, ends with `>` like `https://jmmv.dev//feed.xml>` after cleaning, feed works correctly https://jmmv.dev/feed.xml
* `'` present like `https://jasonraimondi.com/'/index.xml'>` after cleaning, feed works correctly https://jasonraimondi.com/index.xml

**Comment by outcoldman** [comment]
Lol, people do not care at all what they put in their HTML

If you started using double quotes, why switch to single on one of the attributes?

```
<link rel="alternate" type="application/rss+xml" title="Software Engineer" href='/index.xml'>
```

Or let's save on the spaces and quotes in general.

```
<link rel=alternate type=application/rss+xml title="Julio Merino (jmmv.dev)" href=/feed.xml>
```
